CTA update
torontoadvotech/website pull request #111
Opened 2020-11-29 15:13 UTC by bekahjaned

Added gradient to primary and secondary buttons on Home page
<img width="478" alt="Screen Shot 2020-11-29 at 9 56 56 AM" src="https://user-images.githubusercontent.com/47946917/100545690-160f0e00-322b-11eb-9705-6548cd053de9.png">
<img width="547" alt="Screen Shot 2020-11-29 at 9 57 02 AM" src="https://user-images.githubusercontent.com/47946917/100545691-160f0e00-322b-11eb-9f31-593a7cc492cd.png">

2020-11-29 21:44 UTC, MarkCortejos requested changes
just some merging fragments that need to be cleaned up. thanks!

2020-11-29 21:45 UTC, MarkCortejos commented on styles/styles.css
> +<<<<<<< HEAD
please delete

2020-11-29 21:45 UTC, MarkCortejos commented on styles/styles.css
> +=======
please delete

2020-11-29 21:46 UTC, MarkCortejos commented on styles/styles.css
> +>>>>>>> 40d63d8415701a0dec66428b3f024816df832a3b
please delete

2020-11-30 02:52 UTC, bekahjaned commented
Cleaned up merging fragments.

2020-11-30 14:42 UTC, MarkCortejos approved these changes

2020-11-30 14:42 UTC, merged